In [2]:
import pandas as pd
from statistics import mean 
from numpy import std 
import os
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

colors = sns.color_palette("Set2", 4)
sns.set_style("ticks")
sns.despine()

In [3]:
seed_list = ["33", "66", "99"]
seed_list_avg = ["33", "66", "99", "avg", "std"]
result_folder = "../output/classification_model/"
pdf_folder = "pdf"
csv_folder = "csv"

In [4]:
classification_scenario_dict = {
    "Initial": {
    "precision": {"glioma": [0.91, 0.92, 0.97], 
                  "meningioma": [0.85, 0.83, 0.81], 
                  "notumor": [0.97, 1.00, 0.98], 
                  "pituitary": [0.99, 0.96, 0.98]},
    "recall": {"glioma": [0.94, 0.91, 0.89], 
               "meningioma": [0.89, 0.83, 0.93], 
               "notumor": [0.98, 0.99, 0.99], 
               "pituitary": [0.92, 0.97, 0.94]},
    "f1-score": {"glioma": [0.93, 0.92, 0.93], 
                 "meningioma": [0.87, 0.83, 0.87], 
                 "notumor": [0.97, 0.99, 0.98], 
                 "pituitary": [0.96, 0.97, 0.96]}
},
    "Sc. 1": {
    "precision": {"glioma": [0.81, 0.97, 0.99], 
                  "meningioma": [0.83, 0.80, 0.72], 
                  "notumor": [0.98, 0.99, 0.99], 
                  "pituitary": [0.98, 0.85, 0.96]},
    "recall": {"glioma": [0.97, 0.86, 0.77], 
               "meningioma": [0.69, 0.92, 0.94], 
               "notumor": [0.99, 0.99, 0.99], 
               "pituitary": [0.90, 0.97, 0.98]},
    "f1-score": {"glioma": [0.89, 0.91, 0.87], 
                 "meningioma": [0.75, 0.86, 0.82], 
                 "notumor": [0.98, 0.99, 0.99], 
                 "pituitary": [0.94, 0.96, 0.97]}
},
    "Sc. 2 (+11%)": {
    "precision": {"glioma": [0.89, 0.95, 0.97], 
                  "meningioma": [0.90, 0.83, 0.69], 
                  "notumor": [0.98, 0.98, 0.97], 
                  "pituitary": [0.95, 0.98, 0.98]},
    "recall": {"glioma": [0.96, 0.91, 0.78], 
               "meningioma": [0.74, 0.88, 0.92], 
               "notumor": [0.99, 1.00, 0.98], 
               "pituitary": [0.99, 0.96, 0.94]},
    "f1-score": {"glioma": [0.92, 0.93, 0.86], 
                 "meningioma": [0.81, 0.86, 0.79], 
                 "notumor": [0.98, 0.99, 0.98], 
                 "pituitary": [0.97, 0.97, 0.96]}
},
    "Sc. 2 (+25%)": {
    "precision": {"glioma": [0.98, 0.96, 0.99], 
                  "meningioma": [0.82, 0.73, 0.71], 
                  "notumor": [1.00, 0.99, 1.00], 
                  "pituitary": [0.91, 0.99, 0.97]},
    "recall": {"glioma": [0.87, 0.83, 0.81], 
               "meningioma": [0.85, 0.94, 0.96], 
               "notumor": [1.00, 1.00, 0.98], 
               "pituitary": [0.99, 0.94, 0.93]},
    "f1-score": {"glioma": [0.92, 0.89, 0.89], 
                 "meningioma": [0.83, 0.82, 0.82], 
                 "notumor": [1.00, 0.99, 0.99], 
                 "pituitary": [0.95, 0.96, 0.95]}
}
,
    "Sc. 2 (+50%)": {
    "precision": {"glioma": [0.87, 0.96, 0.87], 
                  "meningioma": [0.89, 0.70, 0.83], 
                  "notumor": [0.95, 1.00, 0.99], 
                  "pituitary": [0.97, 0.99, 0.98]},
    "recall": {"glioma": [0.96, 0.84, 0.97], 
               "meningioma": [0.76, 0.93, 0.84], 
               "notumor": [1.00, 0.99, 0.89], 
               "pituitary": [0.92, 0.88, 0.93]},
    "f1-score": {"glioma": [0.91, 0.90, 0.92], 
                 "meningioma": [0.82, 0.80, 0.83], 
                 "notumor": [0.97, 0.99, 0.94], 
                 "pituitary": [0.94, 0.83, 0.95]}
},
    "Sc. 3 (+11%)": {
    "precision": {"glioma": [0.96, 0.91, 0.93], 
                  "meningioma": [0.83, 0.83, 0.78], 
                  "notumor": [0.99, 0.98, 0.99], 
                  "pituitary": [0.95, 0.96, 0.98]},
    "recall": {"glioma": [0.90, 0.90, 0.90], 
               "meningioma": [0.88, 0.81, 0.89], 
               "notumor": [0.98, 1.00, 0.99], 
               "pituitary": [0.98, 0.97, 0.92]},
    "f1-score": {"glioma": [0.93, 0.91, 0.91], 
                 "meningioma": [0.85, 0.82, 0.83], 
                 "notumor": [0.99, 0.99, 0.99], 
                 "pituitary": [0.97, 0.96, 0.95]}
},
    "Sc. 3 (+25%)": {
    "precision": {"glioma": [0.94, 0.97, 0.98], 
                  "meningioma": [0.92, 0.80, 0.66], 
                  "notumor": [0.98, 0.99, 0.97], 
                  "pituitary": [0.92, 0.98, 0.98]},
    "recall": {"glioma": [0.95, 0.89, 0.74], 
               "meningioma": [0.79, 0.93, 0.94], 
               "notumor": [1.00, 0.99, 1.00], 
               "pituitary": [0.99, 0.95, 0.91]},
    "f1-score": {"glioma": [0.94, 0.93, 0.84], 
                 "meningioma": [0.85, 0.86, 0.78], 
                 "notumor": [0.99, 0.99, 0.98], 
                 "pituitary": [0.95, 0.97, 0.94]}
},
    "Sc. 3 (+50%)": {
    "precision": {"glioma": [0.98, 0.96, 0.99], 
                  "meningioma": [0.76, 0.68, 0.72], 
                  "notumor": [0.97, 0.99, 0.99], 
                  "pituitary": [0.91, 0.98, 0.97]},
    "recall": {"glioma": [0.81, 0.89, 0.78], 
               "meningioma": [0.85, 0.94, 0.94], 
               "notumor": [0.99, 1.00, 0.97], 
               "pituitary": [0.99, 0.80, 0.98]},
    "f1-score": {"glioma": [0.88, 0.92, 0.87], 
                 "meningioma": [0.80, 0.79, 0.81], 
                 "notumor": [0.98, 0.99, 0.98], 
                 "pituitary": [0.95, 0.88, 0.98]}
},
    "Sc. 4 (+200 img)": {
    "precision": {"glioma": [0.96, 0.90, 0.90], 
                  "meningioma": [0.86, 0.65, 0.88], 
                  "notumor": [0.94, 0.99, 0.98], 
                  "pituitary": [0.93, 0.97, 0.98]},
    "recall": {"glioma": [0.90, 0.90, 0.96], 
               "meningioma": [0.82, 0.89, 0.80], 
               "notumor": [1.00, 0.98, 1.00], 
               "pituitary": [0.98, 0.74, 0.96]},
    "f1-score": {"glioma": [0.93, 0.90, 0.93], 
                 "meningioma": [0.84, 0.75, 0.84], 
                 "notumor": [0.97, 0.98, 0.99], 
                 "pituitary": [0.96, 0.84, 0.97]}
},
    "Sc. 4 (+400 img)": {
    "precision": {"glioma": [0.95, 0.87, 0.94], 
                  "meningioma": [0.84, 0.80, 0.85], 
                  "notumor": [0.99, 0.99, 0.98], 
                  "pituitary": [0.98, 0.96, 0.94]},
    "recall": {"glioma": [0.93, 0.88, 0.91], 
               "meningioma": [0.90, 0.77, 0.85], 
               "notumor": [1.00, 0.99, 0.99], 
               "pituitary": [0.94, 0.96, 0.97]},
    "f1-score": {"glioma": [0.94, 0.87, 0.93], 
                 "meningioma": [0.87, 0.78, 0.85], 
                 "notumor": [0.99, 0.99, 0.98], 
                 "pituitary": [0.96, 0.96, 0.96]}
},
    "Sc. 4 (+600 img)": {
    "precision": {"glioma": [0.99, 0.89, 0.96], 
                  "meningioma": [0.81, 0.80, 0.83], 
                  "notumor": [0.97, 0.98, 0.99], 
                  "pituitary": [0.97, 0.97, 0.98]},
    "recall": {"glioma": [0.87, 0.92, 0.91], 
               "meningioma": [0.93, 0.83, 0.91], 
               "notumor": [1.00, 0.96, 1.00], 
               "pituitary": [0.98, 0.93, 0.95]},
    "f1-score": {"glioma": [0.93, 0.90, 0.93], 
                 "meningioma": [0.86, 0.81, 0.87], 
                 "notumor": [0.98, 0.97, 0.99], 
                 "pituitary": [0.98, 0.95, 0.96]}
}, 
    "Sc. 6": {
    "precision": {"glioma": [0.88, 0.91, 0.93], 
                  "meningioma": [0.58, 0.50, 0.52], 
                  "notumor": [0.87, 0.96, 0.85], 
                  "pituitary": [0.88, 0.84, 0.88]},
    "recall": {"glioma": [0.71, 0.58, 0.73], 
               "meningioma": [0.75, 0.83, 0.78], 
               "notumor": [0.95, 0.87, 0.91], 
               "pituitary": [0.80, 0.81, 0.71]},
    "f1-score": {"glioma": [0.79, 0.71, 0.82], 
                 "meningioma": [0.66, 0.62, 0.62], 
                 "notumor": [0.91, 0.92, 0.88], 
                 "pituitary": [0.84, 0.82, 0.79]}
}
}

In [5]:
classification5_dict = {
    "initial" : {
    "precision": {"glioma": [0.88, 0.96, 0.97], 
                  "meningioma": [0.84, 0.82, 0.76], 
                  "notumor": [0.97, 0.98, 0.97], 
                  "pituitary": [0.95, 0.95, 0.96]},
    "recall": {"glioma": [0.93, 0.88, 0.87], 
               "meningioma": [0.74, 0.85, 0.89], 
               "notumor": [0.98, 1.00, 0.99], 
               "pituitary": [0.97, 0.99, 0.93]},
    "f1-score": {"glioma": [0.90, 0.91, 0.91], 
                 "meningioma": [0.79, 0.84, 0.82], 
                 "notumor": [0.98, 0.99, 0.98], 
                 "pituitary": [0.96, 0.97, 0.94]}
}, 
 "fine-tuned": {
    "precision": {"glioma": [0.98, 0.96, 0.99], 
                  "meningioma": [0.73, 0.85, 0.72], 
                  "notumor": [0.97, 0.97, 0.96], 
                  "pituitary": [0.97, 0.97, 0.92]},
    "recall": {"glioma": [0.81, 0.92, 0.76], 
               "meningioma": [0.92, 0.87, 0.86], 
               "notumor": [1.00, 0.99, 0.99], 
               "pituitary": [0.95, 0.97, 0.99]},
    "f1-score": {"glioma": [0.89, 0.94, 0.86], 
                 "meningioma": [0.82, 0.86, 0.78], 
                 "notumor": [0.98, 0.98, 0.98], 
                 "pituitary": [0.96, 0.97, 0.95]}
}
}

In [55]:
accuracy_dict = {
    "Initial": [0.93, 0.93, 0.94],
    "Sc. 1": [0.90, 0.93, 0.91],
    "Sc. 2 (+11%)": [0.93, 0.94, 0.90],
    "Sc. 2 (+25%)": [0.93, 0.92, 0.91],
    "Sc. 2 (+50%)": [0.92, 0.90, 0.91],
    "Sc. 3 (+11%)": [0.94, 0.92, 0.92],
    "Sc. 3 (+25%)": [0.94, 0.94, 0.88],
    "Sc. 3 (+50%)": [0.91, 0.90, 0.91],
    "Sc. 4 (+200 img)": [0.93, 0.87, 0.94],
    "Sc. 4 (+400 img)": [0.94, 0.91, 0.93],
    "Sc. 4 (+600 img)": [0.94, 0.91, 0.94],
    "Sc. 6": [0.80, 0.76, 0.77]
}

In [69]:
accuracy_sc5_dict = {
    "Initial": [0.91, 0.93, 0.92],
    "fine-tuned": [0.91, 0.94, 0.90]
}

## Putting all classification metrics into df/csv

In [6]:
def get_all_values_in_df(classification_scenario_dict):
    """ Putting all values (three different seeds) that are currently saved in a dict inside one df.
     For every Scenario, Metric and Class """
    all_values_df = pd.DataFrame()
    for scenario in classification_scenario_dict:
        df = pd.DataFrame()
        for metric in classification_scenario_dict[scenario]:
            for class_name in classification_scenario_dict[scenario][metric]:
                for i in range(3):
                    seed = classification_scenario_dict[scenario][metric][class_name][i]
                    tmp_df = pd.DataFrame(data=[{"Scenario": scenario, "Class": class_name, "Metric": metric, "Measurement": seed}])
                    df = pd.concat([df, tmp_df], axis=0)
        all_values_df = pd.concat([all_values_df, df], axis=0)
    return all_values_df

In [7]:
def get_avg_std_metric_df(avg_metrics, scenario):
    """Get an avg and std for every metric in the df. For every Scenario, Metric and Class."""
    avg_std_values_df = pd.DataFrame(columns=["Scenario", "Class", "Metric", "avg", "std"])
    for metric in avg_metrics:
        for class_name in avg_metrics[metric]:
            seed_33 = avg_metrics[metric][class_name][0]
            seed_66 = avg_metrics[metric][class_name][1]
            seed_99 = avg_metrics[metric][class_name][2]
            tmp_df = pd.DataFrame(data=[{"Scenario": scenario, "Class": class_name, "Metric": metric, "avg": round(mean([seed_33, seed_66, seed_99]), 2), "std": round(std([seed_33, seed_66, seed_99]), 3)}])
            avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)
    #avg_std_values_df.to_csv(result_folder + csv_folder + "/" + file_name.replace(" ", "_") + "_metrics.csv")
    return avg_std_values_df

In [8]:
def get_accuracy_df(accuracy, file_name):
    accuracy_df = pd.DataFrame()
    for i in range(0, len(seed_list)):
        accuracy_df.loc["accuracy", seed_list[i]] = accuracy[i]
    accuracy_df.loc["accuracy", "avg"] = round(mean(accuracy), 2)
    accuracy_df.loc["accuracy", "std"] = round(std(accuracy), 3)
    path_to_results = result_folder
    if not os.path.exists(path_to_results):
        os.mkdir(path_to_results)
    accuracy_df.to_csv(result_folder + csv_folder + "/" + file_name.replace(" ", "_") + "_accuracy.csv")
    return accuracy_df

In [9]:
def get_df_from_dict(avg_metrics, file_name):
    avg_std_values_df = pd.DataFrame(index=avg_metrics.keys(), columns=pd.MultiIndex.from_product([list(avg_metrics[list(avg_metrics.keys())[0]].keys()), seed_list_avg], names=["metrics", "seed"]))

    for metric in avg_metrics:
        for class_name in avg_metrics[metric]:
            seed_33 = avg_metrics[metric][class_name][0]
            seed_66 = avg_metrics[metric][class_name][1]
            seed_99 = avg_metrics[metric][class_name][2]
            avg_std_values_df.loc[metric, (class_name, "33")] = seed_33
            avg_std_values_df.loc[metric, (class_name, "66")] = seed_66
            avg_std_values_df.loc[metric, (class_name, "99")] = seed_99
            avg_std_values_df.loc[metric, (class_name, "avg")] = round(mean([seed_33, seed_66, seed_99]), 2)
            avg_std_values_df.loc[metric, (class_name, "std")] = round(std([seed_33, seed_66, seed_99]), 3)
    avg_std_values_df.to_csv(result_folder + csv_folder + "/" + file_name.replace(" ", "_") + "_metrics.csv")
    return avg_std_values_df

## Initial classification

In [10]:
classification_name = "initial classification"
avg_metrics = {
    "precision": {"glioma": [0.91, 0.92, 0.97], 
                  "meningioma": [0.85, 0.83, 0.81], 
                  "notumor": [0.97, 1.00, 0.98], 
                  "pituitary": [0.99, 0.96, 0.98]},
    "recall": {"glioma": [0.94, 0.91, 0.89], 
               "meningioma": [0.89, 0.83, 0.93], 
               "notumor": [0.98, 0.99, 0.99], 
               "pituitary": [0.92, 0.97, 0.94]},
    "f1-score": {"glioma": [0.93, 0.92, 0.93], 
                 "meningioma": [0.87, 0.83, 0.87], 
                 "notumor": [0.97, 0.99, 0.98], 
                 "pituitary": [0.96, 0.97, 0.96]}
}
accuracy = [0.93, 0.93, 0.94]

In [11]:
get_df_from_dict(avg_metrics, classification_name)

metrics   glioma                          meningioma                           \
seed          33    66    99   avg    std         33    66    99   avg    std
precision   0.91  0.92  0.97  0.93  0.026       0.85  0.83  0.81  0.83  0.016
recall      0.94  0.91  0.89  0.91  0.021       0.89  0.83  0.93  0.88  0.041
f1-score    0.93  0.92  0.93  0.93  0.005       0.87  0.83  0.87  0.86  0.019

metrics   notumor                          pituitary
seed           33    66    99   avg    std        33    66    99   avg    std
precision    0.97   1.0  0.98  0.98  0.012      0.99  0.96  0.98  0.98  0.012
recall       0.98  0.99  0.99  0.99  0.005      0.92  0.97  0.94  0.94  0.021
f1-score     0.97  0.99  0.98  0.98  0.008      0.96  0.97  0.96  0.96  0.005

In [12]:
get_accuracy_df(accuracy, classification_name)

            33    66    99   avg    std
accuracy  0.93  0.93  0.94  0.93  0.005

## Only synthetic classification

In [13]:
classification_name = "only synthetic classification"
avg_metrics = {
    "precision": {"glioma": [0.88, 0.91, 0.93], 
                  "meningioma": [0.58, 0.50, 0.52], 
                  "notumor": [0.87, 0.96, 0.85], 
                  "pituitary": [0.88, 0.84, 0.88]},
    "recall": {"glioma": [0.71, 0.58, 0.73], 
               "meningioma": [0.75, 0.83, 0.78], 
               "notumor": [0.95, 0.87, 0.91], 
               "pituitary": [0.80, 0.81, 0.71]},
    "f1-score": {"glioma": [0.79, 0.71, 0.82], 
                 "meningioma": [0.66, 0.62, 0.62], 
                 "notumor": [0.91, 0.92, 0.88], 
                 "pituitary": [0.84, 0.82, 0.79]}
}

accuracy = [0.80, 0.76, 0.77]

In [14]:
get_df_from_dict(avg_metrics, classification_name)

metrics   glioma                          meningioma                           \
seed          33    66    99   avg    std         33    66    99   avg    std
precision   0.88  0.91  0.93  0.91  0.021       0.58   0.5  0.52  0.53  0.034
recall      0.71  0.58  0.73  0.67  0.066       0.75  0.83  0.78  0.79  0.033
f1-score    0.79  0.71  0.82  0.77  0.046       0.66  0.62  0.62  0.63  0.019

metrics   notumor                          pituitary
seed           33    66    99   avg    std        33    66    99   avg    std
precision    0.87  0.96  0.85  0.89  0.048      0.88  0.84  0.88  0.87  0.019
recall       0.95  0.87  0.91  0.91  0.033       0.8  0.81  0.71  0.77  0.045
f1-score     0.91  0.92  0.88   0.9  0.017      0.84  0.82  0.79  0.82  0.021

In [15]:
get_accuracy_df(accuracy, classification_name)

           33    66    99   avg    std
accuracy  0.8  0.76  0.77  0.78  0.017

## synthetic classification 1

In [16]:
classification_name = "synthetic classification 1"
avg_metrics = {
    "precision": {"glioma": [0.81, 0.97, 0.99], 
                  "meningioma": [0.83, 0.80, 0.72], 
                  "notumor": [0.98, 0.99, 0.99], 
                  "pituitary": [0.98, 0.85, 0.96]},
    "recall": {"glioma": [0.97, 0.86, 0.77], 
               "meningioma": [0.69, 0.92, 0.94], 
               "notumor": [0.99, 0.99, 0.99], 
               "pituitary": [0.90, 0.97, 0.98]},
    "f1-score": {"glioma": [0.89, 0.91, 0.87], 
                 "meningioma": [0.75, 0.86, 0.82], 
                 "notumor": [0.98, 0.99, 0.99], 
                 "pituitary": [0.94, 0.96, 0.97]}
}
accuracy = [0.90, 0.93, 0.91]

In [17]:
get_df_from_dict(avg_metrics, classification_name)

metrics   glioma                          meningioma                           \
seed          33    66    99   avg    std         33    66    99   avg    std
precision   0.81  0.97  0.99  0.92  0.081       0.83   0.8  0.72  0.78  0.046
recall      0.97  0.86  0.77  0.87  0.082       0.69  0.92  0.94  0.85  0.113
f1-score    0.89  0.91  0.87  0.89  0.016       0.75  0.86  0.82  0.81  0.045

metrics   notumor                          pituitary
seed           33    66    99   avg    std        33    66    99   avg    std
precision    0.98  0.99  0.99  0.99  0.005      0.98  0.85  0.96  0.93  0.057
recall       0.99  0.99  0.99  0.99    0.0       0.9  0.97  0.98  0.95  0.036
f1-score     0.98  0.99  0.99  0.99  0.005      0.94  0.96  0.97  0.96  0.012

In [18]:
get_accuracy_df(accuracy, classification_name)

           33    66    99   avg    std
accuracy  0.9  0.93  0.91  0.91  0.012

## synthetic classification 2.1

In [19]:
classification_name = "synthetic classification 2.1"
avg_metrics = {
    "precision": {"glioma": [0.89, 0.95, 0.97], 
                  "meningioma": [0.90, 0.83, 0.69], 
                  "notumor": [0.98, 0.98, 0.97], 
                  "pituitary": [0.95, 0.98, 0.98]},
    "recall": {"glioma": [0.96, 0.91, 0.78], 
               "meningioma": [0.74, 0.88, 0.92], 
               "notumor": [0.99, 1.00, 0.98], 
               "pituitary": [0.99, 0.96, 0.94]},
    "f1-score": {"glioma": [0.92, 0.93, 0.86], 
                 "meningioma": [0.81, 0.86, 0.79], 
                 "notumor": [0.98, 0.99, 0.98], 
                 "pituitary": [0.97, 0.97, 0.96]}
}
accuracy = [0.93, 0.94, 0.90]

In [20]:
get_df_from_dict(avg_metrics, classification_name)

metrics   glioma                          meningioma                           \
seed          33    66    99   avg    std         33    66    99   avg    std
precision   0.89  0.95  0.97  0.94  0.034        0.9  0.83  0.69  0.81  0.087
recall      0.96  0.91  0.78  0.88  0.076       0.74  0.88  0.92  0.85  0.077
f1-score    0.92  0.93  0.86   0.9  0.031       0.81  0.86  0.79  0.82  0.029

metrics   notumor                          pituitary
seed           33    66    99   avg    std        33    66    99   avg    std
precision    0.98  0.98  0.97  0.98  0.005      0.95  0.98  0.98  0.97  0.014
recall       0.99   1.0  0.98  0.99  0.008      0.99  0.96  0.94  0.96  0.021
f1-score     0.98  0.99  0.98  0.98  0.005      0.97  0.97  0.96  0.97  0.005

In [21]:
get_accuracy_df(accuracy, classification_name)

            33    66   99   avg    std
accuracy  0.93  0.94  0.9  0.92  0.017

## synthetic classification 2.2

In [22]:
classification_name = "synthetic classification 2.2"
avg_metrics = {
    "precision": {"glioma": [0.98, 0.96, 0.99], 
                  "meningioma": [0.82, 0.73, 0.71], 
                  "notumor": [1.00, 0.99, 1.00], 
                  "pituitary": [0.91, 0.99, 0.97]},
    "recall": {"glioma": [0.87, 0.83, 0.81], 
               "meningioma": [0.85, 0.94, 0.96], 
               "notumor": [1.00, 1.00, 0.98], 
               "pituitary": [0.99, 0.94, 0.93]},
    "f1-score": {"glioma": [0.92, 0.89, 0.89], 
                 "meningioma": [0.83, 0.82, 0.82], 
                 "notumor": [1.00, 0.99, 0.99], 
                 "pituitary": [0.95, 0.96, 0.95]}
}
accuracy = [0.93, 0.92, 0.91]

In [23]:
get_df_from_dict(avg_metrics, classification_name)

metrics   glioma                          meningioma                           \
seed          33    66    99   avg    std         33    66    99   avg    std
precision   0.98  0.96  0.99  0.98  0.012       0.82  0.73  0.71  0.75  0.048
recall      0.87  0.83  0.81  0.84  0.025       0.85  0.94  0.96  0.92  0.048
f1-score    0.92  0.89  0.89   0.9  0.014       0.83  0.82  0.82  0.82  0.005

metrics   notumor                          pituitary
seed           33    66    99   avg    std        33    66    99   avg    std
precision     1.0  0.99   1.0   1.0  0.005      0.91  0.99  0.97  0.96  0.034
recall        1.0   1.0  0.98  0.99  0.009      0.99  0.94  0.93  0.95  0.026
f1-score      1.0  0.99  0.99  0.99  0.005      0.95  0.96  0.95  0.95  0.005

In [24]:
get_accuracy_df(accuracy, classification_name)

            33    66    99   avg    std
accuracy  0.93  0.92  0.91  0.92  0.008

## synthetic classification 2.3

In [25]:
classification_name = "synthetic classification 2.3"
avg_metrics = {
    "precision": {"glioma": [0.87, 0.96, 0.87], 
                  "meningioma": [0.89, 0.70, 0.83], 
                  "notumor": [0.95, 1.00, 0.99], 
                  "pituitary": [0.97, 0.99, 0.98]},
    "recall": {"glioma": [0.96, 0.84, 0.97], 
               "meningioma": [0.76, 0.93, 0.84], 
               "notumor": [1.00, 0.99, 0.89], 
               "pituitary": [0.92, 0.88, 0.93]},
    "f1-score": {"glioma": [0.91, 0.90, 0.92], 
                 "meningioma": [0.82, 0.80, 0.83], 
                 "notumor": [0.97, 0.99, 0.94], 
                 "pituitary": [0.94, 0.83, 0.95]}
}
accuracy = [0.92, 0.90, 0.91]

In [26]:
get_df_from_dict(avg_metrics, classification_name)

metrics   glioma                          meningioma                           \
seed          33    66    99   avg    std         33    66    99   avg    std
precision   0.87  0.96  0.87   0.9  0.042       0.89   0.7  0.83  0.81  0.079
recall      0.96  0.84  0.97  0.92  0.059       0.76  0.93  0.84  0.84  0.069
f1-score    0.91   0.9  0.92  0.91  0.008       0.82   0.8  0.83  0.82  0.012

metrics   notumor                          pituitary
seed           33    66    99   avg    std        33    66    99   avg    std
precision    0.95   1.0  0.99  0.98  0.022      0.97  0.99  0.98  0.98  0.008
recall        1.0  0.99  0.89  0.96   0.05      0.92  0.88  0.93  0.91  0.022
f1-score     0.97  0.99  0.94  0.97  0.021      0.94  0.83  0.95  0.91  0.054

In [27]:
get_accuracy_df(accuracy, classification_name)

            33   66    99   avg    std
accuracy  0.92  0.9  0.91  0.91  0.008

## synthetic classification 3.1

In [28]:
classification_name = "synthetic classification 3.1"
avg_metrics = {
    "precision": {"glioma": [0.96, 0.91, 0.93], 
                  "meningioma": [0.83, 0.83, 0.78], 
                  "notumor": [0.99, 0.98, 0.99], 
                  "pituitary": [0.95, 0.96, 0.98]},
    "recall": {"glioma": [0.90, 0.90, 0.90], 
               "meningioma": [0.88, 0.81, 0.89], 
               "notumor": [0.98, 1.00, 0.99], 
               "pituitary": [0.98, 0.97, 0.92]},
    "f1-score": {"glioma": [0.93, 0.91, 0.91], 
                 "meningioma": [0.85, 0.82, 0.83], 
                 "notumor": [0.99, 0.99, 0.99], 
                 "pituitary": [0.97, 0.96, 0.95]}
}

accuracy = [0.94, 0.92, 0.92]

In [29]:
get_df_from_dict(avg_metrics, classification_name)

metrics   glioma                          meningioma                           \
seed          33    66    99   avg    std         33    66    99   avg    std
precision   0.96  0.91  0.93  0.93  0.021       0.83  0.83  0.78  0.81  0.024
recall       0.9   0.9   0.9   0.9    0.0       0.88  0.81  0.89  0.86  0.036
f1-score    0.93  0.91  0.91  0.92  0.009       0.85  0.82  0.83  0.83  0.012

metrics   notumor                          pituitary
seed           33    66    99   avg    std        33    66    99   avg    std
precision    0.99  0.98  0.99  0.99  0.005      0.95  0.96  0.98  0.96  0.012
recall       0.98   1.0  0.99  0.99  0.008      0.98  0.97  0.92  0.96  0.026
f1-score     0.99  0.99  0.99  0.99    0.0      0.97  0.96  0.95  0.96  0.008

In [30]:
get_accuracy_df(accuracy, classification_name)

            33    66    99   avg    std
accuracy  0.94  0.92  0.92  0.93  0.009

## synthetic classification 3.2

In [31]:
classification_name = "synthetic classification 3.2"
avg_metrics = {
    "precision": {"glioma": [0.94, 0.97, 0.98], 
                  "meningioma": [0.92, 0.80, 0.66], 
                  "notumor": [0.98, 0.99, 0.97], 
                  "pituitary": [0.92, 0.98, 0.98]},
    "recall": {"glioma": [0.95, 0.89, 0.74], 
               "meningioma": [0.79, 0.93, 0.94], 
               "notumor": [1.00, 0.99, 1.00], 
               "pituitary": [0.99, 0.95, 0.91]},
    "f1-score": {"glioma": [0.94, 0.93, 0.84], 
                 "meningioma": [0.85, 0.86, 0.78], 
                 "notumor": [0.99, 0.99, 0.98], 
                 "pituitary": [0.95, 0.97, 0.94]}
}

accuracy = [0.94, 0.94, 0.88]

In [32]:
get_df_from_dict(avg_metrics, classification_name)

metrics   glioma                          meningioma                           \
seed          33    66    99   avg    std         33    66    99   avg    std
precision   0.94  0.97  0.98  0.96  0.017       0.92   0.8  0.66  0.79  0.106
recall      0.95  0.89  0.74  0.86  0.088       0.79  0.93  0.94  0.89  0.068
f1-score    0.94  0.93  0.84   0.9  0.045       0.85  0.86  0.78  0.83  0.036

metrics   notumor                          pituitary
seed           33    66    99   avg    std        33    66    99   avg    std
precision    0.98  0.99  0.97  0.98  0.008      0.92  0.98  0.98  0.96  0.028
recall        1.0  0.99   1.0   1.0  0.005      0.99  0.95  0.91  0.95  0.033
f1-score     0.99  0.99  0.98  0.99  0.005      0.95  0.97  0.94  0.95  0.012

In [33]:
get_accuracy_df(accuracy, classification_name)

            33    66    99   avg    std
accuracy  0.94  0.94  0.88  0.92  0.028

## synthetic classification 3.3

In [34]:
classification_name = "synthetic classification 3.3"
avg_metrics = {
    "precision": {"glioma": [0.98, 0.96, 0.99], 
                  "meningioma": [0.76, 0.68, 0.72], 
                  "notumor": [0.97, 0.99, 0.99], 
                  "pituitary": [0.91, 0.98, 0.97]},
    "recall": {"glioma": [0.81, 0.89, 0.78], 
               "meningioma": [0.85, 0.94, 0.94], 
               "notumor": [0.99, 1.00, 0.97], 
               "pituitary": [0.99, 0.80, 0.98]},
    "f1-score": {"glioma": [0.88, 0.92, 0.87], 
                 "meningioma": [0.80, 0.79, 0.81], 
                 "notumor": [0.98, 0.99, 0.98], 
                 "pituitary": [0.95, 0.88, 0.98]}
}

accuracy = [0.91, 0.90, 0.91]

In [35]:
get_df_from_dict(avg_metrics, classification_name)

metrics   glioma                          meningioma                           \
seed          33    66    99   avg    std         33    66    99   avg    std
precision   0.98  0.96  0.99  0.98  0.012       0.76  0.68  0.72  0.72  0.033
recall      0.81  0.89  0.78  0.83  0.046       0.85  0.94  0.94  0.91  0.042
f1-score    0.88  0.92  0.87  0.89  0.022        0.8  0.79  0.81   0.8  0.008

metrics   notumor                          pituitary
seed           33    66    99   avg    std        33    66    99   avg    std
precision    0.97  0.99  0.99  0.98  0.009      0.91  0.98  0.97  0.95  0.031
recall       0.99   1.0  0.97  0.99  0.012      0.99   0.8  0.98  0.92  0.087
f1-score     0.98  0.99  0.98  0.98  0.005      0.95  0.88  0.98  0.94  0.042

In [36]:
get_accuracy_df(accuracy, classification_name)

            33   66    99   avg    std
accuracy  0.91  0.9  0.91  0.91  0.005

## synthetic classification 4.1

In [37]:
classification_name = "synthetic classification 4.1"
avg_metrics = {
    "precision": {"glioma": [0.96, 0.90, 0.90], 
                  "meningioma": [0.86, 0.65, 0.88], 
                  "notumor": [0.94, 0.99, 0.98], 
                  "pituitary": [0.93, 0.97, 0.98]},
    "recall": {"glioma": [0.90, 0.90, 0.96], 
               "meningioma": [0.82, 0.89, 0.80], 
               "notumor": [1.00, 0.98, 1.00], 
               "pituitary": [0.98, 0.74, 0.96]},
    "f1-score": {"glioma": [0.93, 0.90, 0.93], 
                 "meningioma": [0.84, 0.75, 0.84], 
                 "notumor": [0.97, 0.98, 0.99], 
                 "pituitary": [0.96, 0.84, 0.97]}
}

accuracy = [0.93, 0.87, 0.94]

In [38]:
get_df_from_dict(avg_metrics, classification_name)

metrics   glioma                         meningioma                           \
seed          33   66    99   avg    std         33    66    99   avg    std
precision   0.96  0.9   0.9  0.92  0.028       0.86  0.65  0.88   0.8  0.104
recall       0.9  0.9  0.96  0.92  0.028       0.82  0.89   0.8  0.84  0.039
f1-score    0.93  0.9  0.93  0.92  0.014       0.84  0.75  0.84  0.81  0.042

metrics   notumor                          pituitary
seed           33    66    99   avg    std        33    66    99   avg    std
precision    0.94  0.99  0.98  0.97  0.022      0.93  0.97  0.98  0.96  0.022
recall        1.0  0.98   1.0  0.99  0.009      0.98  0.74  0.96  0.89  0.109
f1-score     0.97  0.98  0.99  0.98  0.008      0.96  0.84  0.97  0.92  0.059

In [39]:
get_accuracy_df(accuracy, classification_name)

            33    66    99   avg    std
accuracy  0.93  0.87  0.94  0.91  0.031

## synthetic classification 4.2

In [40]:
classification_name = "synthetic classification 4.2"
avg_metrics = {
    "precision": {"glioma": [0.95, 0.87, 0.94], 
                  "meningioma": [0.84, 0.80, 0.85], 
                  "notumor": [0.99, 0.99, 0.98], 
                  "pituitary": [0.98, 0.96, 0.94]},
    "recall": {"glioma": [0.93, 0.88, 0.91], 
               "meningioma": [0.90, 0.77, 0.85], 
               "notumor": [1.00, 0.99, 0.99], 
               "pituitary": [0.94, 0.96, 0.97]},
    "f1-score": {"glioma": [0.94, 0.87, 0.93], 
                 "meningioma": [0.87, 0.78, 0.85], 
                 "notumor": [0.99, 0.99, 0.98], 
                 "pituitary": [0.96, 0.96, 0.96]}
}

accuracy = [0.94, 0.91, 0.93]

In [41]:
get_df_from_dict(avg_metrics, classification_name)

metrics   glioma                          meningioma                           \
seed          33    66    99   avg    std         33    66    99   avg    std
precision   0.95  0.87  0.94  0.92  0.036       0.84   0.8  0.85  0.83  0.022
recall      0.93  0.88  0.91  0.91  0.021        0.9  0.77  0.85  0.84  0.054
f1-score    0.94  0.87  0.93  0.91  0.031       0.87  0.78  0.85  0.83  0.039

metrics   notumor                          pituitary
seed           33    66    99   avg    std        33    66    99   avg    std
precision    0.99  0.99  0.98  0.99  0.005      0.98  0.96  0.94  0.96  0.016
recall        1.0  0.99  0.99  0.99  0.005      0.94  0.96  0.97  0.96  0.012
f1-score     0.99  0.99  0.98  0.99  0.005      0.96  0.96  0.96  0.96    0.0

In [42]:
get_accuracy_df(accuracy, classification_name)

            33    66    99   avg    std
accuracy  0.94  0.91  0.93  0.93  0.012

## synthetic classification 4.3

In [43]:
classification_name = "synthetic classification 4.3"
avg_metrics = {
    "precision": {"glioma": [0.99, 0.89, 0.96], 
                  "meningioma": [0.81, 0.80, 0.83], 
                  "notumor": [0.97, 0.98, 0.99], 
                  "pituitary": [0.97, 0.97, 0.98]},
    "recall": {"glioma": [0.87, 0.92, 0.91], 
               "meningioma": [0.93, 0.83, 0.91], 
               "notumor": [1.00, 0.96, 1.00], 
               "pituitary": [0.98, 0.93, 0.95]},
    "f1-score": {"glioma": [0.93, 0.90, 0.93], 
                 "meningioma": [0.86, 0.81, 0.87], 
                 "notumor": [0.98, 0.97, 0.99], 
                 "pituitary": [0.98, 0.95, 0.96]}
}

accuracy = [0.94, 0.91, 0.94]

In [44]:
get_df_from_dict(avg_metrics, classification_name)

metrics   glioma                          meningioma                           \
seed          33    66    99   avg    std         33    66    99   avg    std
precision   0.99  0.89  0.96  0.95  0.042       0.81   0.8  0.83  0.81  0.012
recall      0.87  0.92  0.91   0.9  0.022       0.93  0.83  0.91  0.89  0.043
f1-score    0.93   0.9  0.93  0.92  0.014       0.86  0.81  0.87  0.85  0.026

metrics   notumor                          pituitary
seed           33    66    99   avg    std        33    66    99   avg    std
precision    0.97  0.98  0.99  0.98  0.008      0.97  0.97  0.98  0.97  0.005
recall        1.0  0.96   1.0  0.99  0.019      0.98  0.93  0.95  0.95  0.021
f1-score     0.98  0.97  0.99  0.98  0.008      0.98  0.95  0.96  0.96  0.012

In [45]:
get_accuracy_df(accuracy, classification_name)

            33    66    99   avg    std
accuracy  0.94  0.91  0.94  0.93  0.014

# synthetic classification 5

In [46]:
classification_name = "synthetic classification 5"
avg_metrics = {
    "precision": {"glioma": [0.88, 0.96, 0.97], 
                  "meningioma": [0.84, 0.82, 0.76], 
                  "notumor": [0.97, 0.98, 0.97], 
                  "pituitary": [0.95, 0.95, 0.96]},
    "recall": {"glioma": [0.93, 0.88, 0.87], 
               "meningioma": [0.74, 0.85, 0.89], 
               "notumor": [0.98, 1.00, 0.99], 
               "pituitary": [0.97, 0.99, 0.93]},
    "f1-score": {"glioma": [0.90, 0.91, 0.91], 
                 "meningioma": [0.79, 0.84, 0.82], 
                 "notumor": [0.98, 0.99, 0.98], 
                 "pituitary": [0.96, 0.97, 0.94]}
}

accuracy = [0.91, 0.93, 0.92]

In [47]:
get_df_from_dict(avg_metrics, classification_name)

metrics   glioma                          meningioma                           \
seed          33    66    99   avg    std         33    66    99   avg    std
precision   0.88  0.96  0.97  0.94   0.04       0.84  0.82  0.76  0.81  0.034
recall      0.93  0.88  0.87  0.89  0.026       0.74  0.85  0.89  0.83  0.063
f1-score     0.9  0.91  0.91  0.91  0.005       0.79  0.84  0.82  0.82  0.021

metrics   notumor                          pituitary
seed           33    66    99   avg    std        33    66    99   avg    std
precision    0.97  0.98  0.97  0.97  0.005      0.95  0.95  0.96  0.95  0.005
recall       0.98   1.0  0.99  0.99  0.008      0.97  0.99  0.93  0.96  0.025
f1-score     0.98  0.99  0.98  0.98  0.005      0.96  0.97  0.94  0.96  0.012

In [48]:
get_accuracy_df(accuracy, classification_name)

            33    66    99   avg    std
accuracy  0.91  0.93  0.92  0.92  0.008

### Save in one big df

In [65]:
avg_std_metric_df = pd.DataFrame()
for key in classification_scenario_dict:
    tmp_df = get_avg_std_metric_df(classification_scenario_dict[key], key)
    avg_std_metric_df = pd.concat([avg_std_metric_df, tmp_df], axis=0)

avg_std_metric_df.to_csv(result_folder + csv_folder + "/avg_std_metric_all_scenarios_without_sc5.csv", index=False)
avg_std_metric_df.head()

/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)
/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)
/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)
/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)
/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)
/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)
/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)
/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)
/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)
/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)
/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)
/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)

  Scenario       Class     Metric   avg    std
0  Initial      glioma  precision  0.93  0.026
0  Initial  meningioma  precision  0.83  0.016
0  Initial     notumor  precision  0.98  0.012
0  Initial   pituitary  precision  0.98  0.012
0  Initial      glioma     recall  0.91  0.021

In [66]:
all_values_df = get_all_values_in_df(classification_scenario_dict)
all_values_df.to_csv(result_folder + csv_folder + "/all_values_metric_all_scenarios_without_sc5.csv", index=False)
all_values_df.head()

  Scenario       Class     Metric  Measurement
0  Initial      glioma  precision         0.91
0  Initial      glioma  precision         0.92
0  Initial      glioma  precision         0.97
0  Initial  meningioma  precision         0.85
0  Initial  meningioma  precision         0.83

In [67]:
avg_std_metric_sc5_df = pd.DataFrame()
for key in classification5_dict:
    tmp_df = get_avg_std_metric_df(classification5_dict[key], key)
    avg_std_metric_sc5_df = pd.concat([avg_std_metric_sc5_df, tmp_df], axis=0)
avg_std_metric_sc5_df.to_csv(result_folder + csv_folder + "/avg_std_metric_sc5.csv", index=False)
avg_std_metric_sc5_df.head()

/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)
/var/folders/qv/tqh1ls9x7nlgts1pcbvs42140000gn/T/ipykernel_85189/4235953898.py:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  avg_std_values_df = pd.concat([avg_std_values_df, tmp_df], axis=0)

  Scenario       Class     Metric   avg    std
0  initial      glioma  precision  0.94  0.040
0  initial  meningioma  precision  0.81  0.034
0  initial     notumor  precision  0.97  0.005
0  initial   pituitary  precision  0.95  0.005
0  initial      glioma     recall  0.89  0.026

In [68]:
all_values_sc5_df = get_all_values_in_df(classification5_dict)
all_values_sc5_df.to_csv(result_folder + csv_folder + "/all_values_sc5_metric.csv", index=False)
all_values_sc5_df#.head()

      Scenario       Class     Metric  Measurement
0      initial      glioma  precision         0.88
0      initial      glioma  precision         0.96
0      initial      glioma  precision         0.97
0      initial  meningioma  precision         0.84
0      initial  meningioma  precision         0.82
..         ...         ...        ...          ...
0   fine-tuned     notumor   f1-score         0.98
0   fine-tuned     notumor   f1-score         0.98
0   fine-tuned   pituitary   f1-score         0.96
0   fine-tuned   pituitary   f1-score         0.97
0   fine-tuned   pituitary   f1-score         0.95

[72 rows x 4 columns]

### Putting all accuracy values into one df

In [72]:
accuracy_df = pd.DataFrame()
for scenario in accuracy_dict:
    for accuracy in accuracy_dict[scenario]:
        tmp_df = pd.DataFrame(data=[{"Scenario": scenario, "Measurement": accuracy}])
        accuracy_df = pd.concat([accuracy_df, tmp_df], axis=0)
accuracy_df.to_csv(result_folder + csv_folder + "/accuracy_all_scenarios_without_sc5.csv", index=False)
accuracy_df.head()

  Scenario  Measurement
0  Initial         0.93
0  Initial         0.93
0  Initial         0.94
0    Sc. 1         0.90
0    Sc. 1         0.93

In [73]:
accuracy_sc5_df = pd.DataFrame()
for scenario in accuracy_sc5_dict:
    for accuracy in accuracy_sc5_dict[scenario]:
        tmp_df = pd.DataFrame(data=[{"Scenario": scenario, "Measurement": accuracy}])
        accuracy_sc5_df = pd.concat([accuracy_sc5_df, tmp_df], axis=0)
accuracy_sc5_df.to_csv(result_folder + csv_folder + "/accuracy_sc5.csv", index=False)
accuracy_sc5_df#.head()

     Scenario  Measurement
0     Initial         0.91
0     Initial         0.93
0     Initial         0.92
0  fine-tuned         0.91
0  fine-tuned         0.94
0  fine-tuned         0.90